import gradio as gr
import os
from agents.orchestrator import OrchestratorAgent

# Load orchestrator once at startup
orchestrator = OrchestratorAgent()

# Session search history
search_history = []

# ArXiv category mapping
FIELD_CATEGORIES = {
    "AI": "cs.AI cs.LG cs.CL cs.CV cs.NE",
    "Physics": "physics hep-th quant-ph cond-mat astro-ph",
    "Math": "math.AG math.AP math.CO math.ST math.OC",
    "Biology": "q-bio.BM q-bio.GN q-bio.NC q-bio.PE",
    "Other": ""
}

def generate_bibtex(papers: list, topic: str) -> str:
    """Generate a BibTeX file from ranked papers."""
    bibtex = f"% BibTeX citations generated by ResearchNavigator\n"
    bibtex += f"% Topic: {topic}\n\n"

    for paper in papers:
        first_author = paper['authors'][0].split()[-1].lower() if paper['authors'] else "unknown"
        year = paper['published'][:4]
        paper_id = paper['id'].replace(".", "").replace("/", "")
        cite_key = f"{first_author}{year}{paper_id[:4]}"

        bibtex += f"@article{{{cite_key},\n"
        bibtex += f"  title = {{{paper['title']}}},\n"
        bibtex += f"  author = {{{' and '.join(paper['authors'])}}},\n"
        bibtex += f"  year = {{{year}}},\n"
        bibtex += f"  url = {{{paper['url']}}},\n"
        bibtex += f"  note = {{ArXiv preprint}}\n"
        bibtex += f"}}\n\n"

    return bibtex

def format_history() -> str:
    """Format search history for display."""
    if not search_history:
        return "*No searches yet.*"
    history_md = "### Recent Searches\n"
    for i, item in enumerate(reversed(search_history), 1):
        history_md += f"**{i}.** {item['query']} *(found {item['papers']} papers, {item['year_start']}–{item['year_end']})*\n\n"
    return history_md

def run_agent(user_query, field, paper_count, year_start, year_end, progress=gr.Progress()):
    """Called when user clicks the button. Runs the full agent pipeline."""

    if not user_query.strip():
        return "⚠️ Please enter a research topic.", "", "", gr.DownloadButton(visible=False), gr.DownloadButton(visible=False), format_history()

    if year_start > year_end:
        return "⚠️ Start year cannot be greater than end year.", "", "", gr.DownloadButton(visible=False), gr.DownloadButton(visible=False), format_history()

    # Get ArXiv category for selected field
    category = FIELD_CATEGORIES.get(field, "")

    progress(0, desc="Understanding your query...")
    progress(0.1, desc="Understanding your query...")

    result = orchestrator.run(
        user_query,
        paper_count=int(paper_count),
        year_start=int(year_start),
        year_end=int(year_end),
        category=category,
        progress_callback=lambda msg: progress(0.5, desc=msg)
    )

    progress(1.0, desc="✅ Done!")

    if not result["success"]:
        return f"❌ No papers found for **'{user_query}'**. Try a more specific academic topic like 'transformer architecture' or 'federated learning privacy'.", "", "", gr.DownloadButton(visible=False), gr.DownloadButton(visible=False), format_history()

    # Add to search history (keep last 5)
    search_history.append({
        "query": user_query,
        "papers": result["papers_found"],
        "year_start": int(year_start),
        "year_end": int(year_end)
    })
    if len(search_history) > 5:
        search_history.pop(0)

    # Format ranked papers for display
    papers_md = ""
    for i, paper in enumerate(result["papers"], 1):
        score = paper.get("relevance_score", "N/A")
        reason = paper.get("reason", "")
        papers_md += f"""### {i}. {paper['title']}
- **Authors:** {', '.join(paper['authors'])}
- **Published:** {paper['published']}
- **Relevance Score:** {score}/10
- **Why:** {reason}
- [View on ArXiv]({paper['url']})

---
"""

    # Save report to file for download
    report_path = "report.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(result["report"])

    # Save BibTeX to file for download
    bibtex_path = "citations.bib"
    bibtex_content = generate_bibtex(result["papers"], result["topic"])
    with open(bibtex_path, "w", encoding="utf-8") as f:
        f.write(bibtex_content)

    status = f"✅ Analyzed **{int(paper_count)} papers** from ArXiv ({int(year_start)}–{int(year_end)}) · Field: **{field}** · Showing top **{result['papers_found']} most relevant** on: **{result['topic']}**"
    return status, result["report"], papers_md, gr.DownloadButton(value=report_path, visible=True), gr.DownloadButton(value=bibtex_path, visible=True), format_history()


def run_comparison(topic1, topic2, field, paper_count, year_start, year_end, progress=gr.Progress()):
    """Run two topics side by side and compare results."""

    if not topic1.strip() or not topic2.strip():
        return "⚠️ Please enter both topics.", "", ""

    category = FIELD_CATEGORIES.get(field, "")

    progress(0.1, desc=f"Researching '{topic1}'...")
    result1 = orchestrator.run(
        topic1,
        paper_count=int(paper_count),
        year_start=int(year_start),
        year_end=int(year_end),
        category=category
    )

    progress(0.6, desc=f"Researching '{topic2}'...")
    result2 = orchestrator.run(
        topic2,
        paper_count=int(paper_count),
        year_start=int(year_start),
        year_end=int(year_end),
        category=category
    )

    progress(1.0, desc="✅ Comparison ready!")

    status = f"✅ Compared **{topic1}** vs **{topic2}**"

    if result1["success"]:
        left = f"## {result1['topic']}\n"
        left += f"*{result1['papers_found']} papers found*\n\n"
        left += result1["report"]
    else:
        left = f"❌ No papers found for **{topic1}**."

    if result2["success"]:
        right = f"## {result2['topic']}\n"
        right += f"*{result2['papers_found']} papers found*\n\n"
        right += result2["report"]
    else:
        right = f"❌ No papers found for **{topic2}**."

    return status, left, right


# Build UI
with gr.Blocks(title="ResearchNavigator", theme=gr.themes.Soft(), css="""
              .built-with { display: none !important; }
    footer { display: none !important; }
    .svelte-1ipelgc { display: none !important; }
    @import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&display=swap');
    * { font-family: 'Inter', sans-serif !important; }
""") as demo: 

    gr.Markdown("""
# ResearchNavigator
### Multi-Agent Research Discovery & Synthesis System

Enter any research topic → AI agents automatically find, rank, and synthesize the most relevant papers for you.
    """)

    # Field selector
    gr.Markdown("**Choose Field:**")
    field_selector = gr.Radio(
        choices=list(FIELD_CATEGORIES.keys()),
        value="AI",
        label="",
        container=False
    )

    with gr.Row():
        with gr.Column(scale=4):
            query_input = gr.Textbox(
                label="Research Topic",
                placeholder="e.g. 'reinforcement learning from human feedback'",
                lines=2
            )
        with gr.Column(scale=1):
            submit_btn = gr.Button("Analyze", variant="primary", size="lg")

    with gr.Row():
        with gr.Column():
            paper_count = gr.Slider(
                minimum=3,
                maximum=15,
                value=8,
                step=1,
                label="Number of Papers to Analyze"
            )
        with gr.Column():
            year_start = gr.Slider(
                minimum=2000,
                maximum=2026,
                value=2020,
                step=1,
                label="From Year",
                info="Filter papers published from this year"
            )
        with gr.Column():
            year_end = gr.Slider(
                minimum=2000,
                maximum=2026,
                value=2026,
                step=1,
                label="To Year",
                info="Filter papers published up to this year"
            )

    status_out = gr.Markdown(value="*Enter a topic above and click Analyze to get started.*")

    with gr.Tabs():
        with gr.Tab("Synthesis Report"):
            report_out = gr.Markdown()
            with gr.Row():
                download_btn = gr.DownloadButton(
                    label="Download Report (.md)",
                    visible=False
                )
                bibtex_btn = gr.DownloadButton(
                    label="Export Citations (.bib)",
                    visible=False
                )
        with gr.Tab("Ranked Papers"):
            papers_out = gr.Markdown()
        with gr.Tab("Compare Two Topics"):
            gr.Markdown("### Compare two research topics side by side")
            with gr.Row():
                compare_topic1 = gr.Textbox(
                    label="Topic 1",
                    placeholder="e.g. 'federated learning'",
                    lines=2
                )
                compare_topic2 = gr.Textbox(
                    label="Topic 2",
                    placeholder="e.g. 'differential privacy'",
                    lines=2
                )
            compare_btn = gr.Button("Compare Topics", variant="primary")
            compare_status = gr.Markdown()
            with gr.Row():
                compare_left = gr.Markdown()
                compare_right = gr.Markdown()
        with gr.Tab("Search History"):
            history_out = gr.Markdown(value="*No searches yet.*")

    gr.Examples(
        examples=[
            ["reinforcement learning from human feedback"],
            ["large language model reasoning"],
            ["diffusion models image generation"],
            ["graph neural networks drug discovery"],
            ["federated learning privacy"],
        ],
        inputs=query_input
    )

    submit_btn.click(
        fn=run_agent,
        inputs=[query_input, field_selector, paper_count, year_start, year_end],
        outputs=[status_out, report_out, papers_out, download_btn, bibtex_btn, history_out]
    )

    compare_btn.click(
        fn=run_comparison,
        inputs=[compare_topic1, compare_topic2, field_selector, paper_count, year_start, year_end],
        outputs=[compare_status, compare_left, compare_right]
    )

if __name__ == "__main__":
    demo.launch(
        show_error=True,
        show_api=False,
    )
