import gradio as gr
import os
from agents.orchestrator import OrchestratorAgent

# Load orchestrator once at startup
orchestrator = OrchestratorAgent()

def generate_bibtex(papers: list, topic: str) -> str:
    """Generate a BibTeX file from ranked papers."""
    bibtex = f"% BibTeX citations generated by ResearchNavigator\n"
    bibtex += f"% Topic: {topic}\n\n"

    for paper in papers:
        # Create a citation key from first author last name + year
        first_author = paper['authors'][0].split()[-1].lower() if paper['authors'] else "unknown"
        year = paper['published'][:4]
        paper_id = paper['id'].replace(".", "").replace("/", "")
        cite_key = f"{first_author}{year}{paper_id[:4]}"

        bibtex += f"@article{{{cite_key},\n"
        bibtex += f"  title = {{{paper['title']}}},\n"
        bibtex += f"  author = {{{' and '.join(paper['authors'])}}},\n"
        bibtex += f"  year = {{{year}}},\n"
        bibtex += f"  url = {{{paper['url']}}},\n"
        bibtex += f"  note = {{ArXiv preprint}}\n"
        bibtex += f"}}\n\n"

    return bibtex

def run_agent(user_query, paper_count, year_start, year_end, progress=gr.Progress()):
    """Called when user clicks the button. Runs the full agent pipeline."""

    if not user_query.strip():
        return "⚠️ Please enter a research topic.", "", "", gr.DownloadButton(visible=False), gr.DownloadButton(visible=False)

    if year_start > year_end:
        return "⚠️ Start year cannot be greater than end year.", "", "", gr.DownloadButton(visible=False), gr.DownloadButton(visible=False)

    progress(0, desc="Understanding your query...")
    progress(0.1, desc="Understanding your query...")

    result = orchestrator.run(
        user_query,
        paper_count=int(paper_count),
        year_start=int(year_start),
        year_end=int(year_end),
        progress_callback=lambda msg: progress(0.5, desc=msg)
    )

    progress(1.0, desc="✅ Done!")

    if not result["success"]:
        return f"❌ No papers found for **'{user_query}'**. Try a more specific academic topic like 'transformer architecture' or 'federated learning privacy'.", "", "", gr.DownloadButton(visible=False), gr.DownloadButton(visible=False)

    # Format ranked papers for display
    papers_md = ""
    for i, paper in enumerate(result["papers"], 1):
        score = paper.get("relevance_score", "N/A")
        reason = paper.get("reason", "")
        papers_md += f"""### {i}. {paper['title']}
- 👥 **Authors:** {', '.join(paper['authors'])}
- 📅 **Published:** {paper['published']}
- ⭐ **Relevance Score:** {score}/10
- 💡 **Why:** {reason}
- 🔗 [View on ArXiv]({paper['url']})

---
"""

    # Save report to file for download
    report_path = "report.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(result["report"])

    # Save BibTeX to file for download
    bibtex_path = "citations.bib"
    bibtex_content = generate_bibtex(result["papers"], result["topic"])
    with open(bibtex_path, "w", encoding="utf-8") as f:
        f.write(bibtex_content)

    status = f"✅ Analyzed **{int(paper_count)} papers** from ArXiv ({int(year_start)}–{int(year_end)}) · Showing top **{result['papers_found']} most relevant** on: **{result['topic']}**"
    return status, result["report"], papers_md, gr.DownloadButton(value=report_path, visible=True), gr.DownloadButton(value=bibtex_path, visible=True)


# Build UI
with gr.Blocks(title="ResearchNavigator", theme=gr.themes.Soft(), css="""
    .built-with { display: none !important; }
    footer { display: none !important; }
    .svelte-1ipelgc { display: none !important; }
""") as demo:

    gr.Markdown("""
# ResearchNavigator
### Multi-Agent Literature Review System

Enter any research topic → AI agents automatically find, rank, and synthesize the most relevant papers for you.
    """)

    with gr.Row():
        with gr.Column(scale=4):
            query_input = gr.Textbox(
                label="Research Topic",
                placeholder="e.g. 'reinforcement learning from human feedback'",
                lines=2
            )
        with gr.Column(scale=1):
            submit_btn = gr.Button("Research This", variant="primary", size="lg")

    with gr.Row():
        with gr.Column():
            paper_count = gr.Slider(
                minimum=3,
                maximum=15,
                value=8,
                step=1,
                label="Number of Papers to Analyze",
                info="More papers = deeper analysis but slower"
            )
        with gr.Column():
            year_start = gr.Slider(
                minimum=2000,
                maximum=2026,
                value=2020,
                step=1,
                label="From Year",
                info="Filter papers published from this year"
            )
        with gr.Column():
            year_end = gr.Slider(
                minimum=2000,
                maximum=2026,
                value=2026,
                step=1,
                label="To Year",
                info="Filter papers published up to this year"
            )

    status_out = gr.Markdown(value="*Enter a topic above and click Research This to get started.*")

    with gr.Tabs():
        with gr.Tab("Synthesis Report"):
            report_out = gr.Markdown()
            with gr.Row():
                download_btn = gr.DownloadButton(
                    label="Download Report (.md)",
                    visible=False
                )
                bibtex_btn = gr.DownloadButton(
                    label="Export Citations (.bib)",
                    visible=False
                )
        with gr.Tab("Ranked Papers"):
            papers_out = gr.Markdown()

    gr.Examples(
        examples=[
            ["reinforcement learning from human feedback"],
            ["large language model reasoning"],
            ["diffusion models image generation"],
            ["graph neural networks drug discovery"],
            ["federated learning privacy"],
        ],
        inputs=query_input
    )

    submit_btn.click(
        fn=run_agent,
        inputs=[query_input, paper_count, year_start, year_end],
        outputs=[status_out, report_out, papers_out, download_btn, bibtex_btn]
    )

if __name__ == "__main__":
    demo.launch(
        show_error=True,
        show_api=False,
    )
